apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: wordpress-alerts
  namespace: monitoring
spec:
  groups:
    - name: wordpress-alerts
      rules:
        - alert: HighPodCPU
          expr: sum(rate(container_cpu_usage_seconds_total{namespace="default",pod=~"wordpress-.*"}[1m])) by (pod) > 0.5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected for WordPress pods"
            description: "Pod {{ $labels.pod }} is using high CPU"
        - alert: HighNginx5xxErrors
          expr: sum(rate(nginx_ingress_controller_requests{namespace="default",ingress="my-release-nginx",status=~"5.."}[1m])) by (ingress) > 5
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High 5xx error rate for Nginx"
            description: "Nginx ingress {{ $labels.ingress }} has a high rate of 5xx errors"
